// <auto-generated />
using System;
using Mastemis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mastemis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MastemisDbContext))]
    [Migration("20260722081643_AddProblemAuthorScopes")]
    partial class AddProblemAuthorScopes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.AuditRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAtUtc");

                    b.HasIndex("ResourceType", "ResourceId", "OccurredAtUtc");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.CandidateRegistrationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessState")
                        .HasColumnType("integer");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistrationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ExamId", "CandidateId")
                        .IsUnique();

                    b.HasIndex("ExamId", "RegistrationCode")
                        .IsUnique();

                    b.ToTable("candidate_registrations", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.CandidateRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.EvidenceItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousChainHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ServerTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "ServerTimestampUtc");

                    b.ToTable("evidence_items", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.EvidencePackageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("LatestChainHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("ExamId", "RoomId", "CandidateId", "CreatedAtUtc");

                    b.ToTable("evidence_packages", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.EvidenceReviewGrantRow", b =>
                {
                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("PackageId", "ReviewerId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("evidence_review_grants", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.ExamAssignmentRow", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExamId", "UserId", "Role");

                    b.HasIndex("UserId", "ExamId");

                    b.ToTable("exam_user_assignments", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.ExamRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("State", "StartsAtUtc");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.IdempotencyRow", b =>
                {
                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Caller")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Operation", "Caller", "Key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.JudgeJobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaximumAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("State", "LeaseExpiresAtUtc");

                    b.HasIndex("State", "Priority", "AvailableAtUtc", "CreatedAtUtc");

                    b.ToTable("judge_jobs", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.JudgeWorkerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SandboxBackend")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeatUtc");

                    b.ToTable("judge_workers", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.JudgementRow", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckerDiagnosticSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("CompilerDiagnosticSummary")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExecutionMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<int?>("FailedTestIndex")
                        .HasColumnType("integer");

                    b.Property<string>("JudgeVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("PeakMemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RuntimeDiagnosticSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SandboxBackend")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int?>("Signal")
                        .HasColumnType("integer");

                    b.Property<long>("StandardErrorBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("StandardOutputBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("SubmissionId");

                    b.HasIndex("WorkerId", "CompletedAtUtc");

                    b.ToTable("judgements", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.OutboxRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.ProblemJudgeProfileRow", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CompilationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<long>("CompilationOutputBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("CpuMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<long>("FileBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("OutputBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ProcessCount")
                        .HasColumnType("integer");

                    b.Property<int>("TestCount")
                        .HasColumnType("integer");

                    b.Property<long>("WallMilliseconds")
                        .HasColumnType("bigint");

                    b.HasKey("ProblemId");

                    b.ToTable("problem_judge_profiles", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.ProblemTestCaseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckerId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("ExpectedBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpectedObjectId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("InputBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("InputObjectId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<int>("TestIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId", "TestIndex")
                        .IsUnique();

                    b.ToTable("problem_test_cases", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ExamProblemAssignmentRow", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("ExamId", "ProblemId");

                    b.HasIndex("ProblemId");

                    b.ToTable("exam_problem_assignments", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.GeneratedTestRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("InputLength")
                        .HasColumnType("bigint");

                    b.Property<string>("InputObjectId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("InputSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("OutputLength")
                        .HasColumnType("bigint");

                    b.Property<string>("OutputObjectId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OutputSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TestIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TestSetId", "TestIndex")
                        .IsUnique();

                    b.ToTable("generated_tests", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.GeneratedTestSetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GenerationOperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenerationOperationId")
                        .IsUnique();

                    b.HasIndex("ProblemId", "Published");

                    b.HasIndex("ProblemId", "Version")
                        .IsUnique();

                    b.ToTable("generated_test_sets", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemAuthorAssignmentRow", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ProblemId", "UserId");

                    b.HasIndex("UserId", "Status", "ExpiresAtUtc");

                    b.ToTable("problem_author_assignments", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemDraftRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MasSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MasSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MemoryLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("OutputLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeLimitMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("problem_drafts", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemGenerationOperationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrngAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublishedTestSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuntimeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Seed")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("ProblemId", "Status");

                    b.ToTable("problem_generation_operations", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemPackageExportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PackageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId", "CreatedAtUtc");

                    b.ToTable("problem_package_exports", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemPackageImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PackageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PackageSha256");

                    b.ToTable("problem_package_imports", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemStatementRow", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProblemId", "Locale");

                    b.HasIndex("ProblemId", "UpdatedAtUtc");

                    b.ToTable("problem_statements", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.RoomAssignmentRow", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoomId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("room_invigilator_assignments", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.RoomRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("ExamId", "Code")
                        .IsUnique();

                    b.ToTable("exam_rooms", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FrozenRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TerminatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "State");

                    b.HasIndex("ExamId", "CandidateId")
                        .IsUnique()
                        .HasFilter("\"State\" IN (1, 2)");

                    b.HasIndex("ExamId", "State");

                    b.HasIndex("RoomId", "State");

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SfeEvaluationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("SessionId", "EvaluatedAtUtc");

                    b.ToTable("sfe_evaluations", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SfeEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ClientSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ClientTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ServerReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ClientSequence")
                        .IsUnique();

                    b.HasIndex("SessionId", "ServerReceivedAtUtc");

                    b.ToTable("sfe_events", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SourceRevisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.ToTable("source_revisions", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SubmissionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"IsFinal\" = TRUE");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.TerminationMetadataRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FinalSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrozenRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JudgeJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarningId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("FinalSubmissionId")
                        .IsUnique();

                    b.HasIndex("JudgeJobId")
                        .IsUnique();

                    b.HasIndex("WarningId")
                        .IsUnique();

                    b.ToTable("termination_metadata", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.WarningRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.HasIndex("SessionId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("ExamId", "RoomId", "CandidateId", "IssuedAtUtc");

                    b.ToTable("confirmed_warnings", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.WorkerCredentialRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "RevokedAtUtc");

                    b.ToTable("worker_credentials", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.CandidateRegistrationRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.CandidateRow", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mastemis.Infrastructure.Persistence.ExamRow", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.EvidenceItemRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.EvidencePackageRow", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.EvidenceReviewGrantRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.EvidencePackageRow", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.JudgeJobRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.SubmissionRow", null)
                        .WithOne()
                        .HasForeignKey("Mastemis.Infrastructure.Persistence.JudgeJobRow", "SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.JudgementRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.SubmissionRow", null)
                        .WithOne()
                        .HasForeignKey("Mastemis.Infrastructure.Persistence.JudgementRow", "SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ExamProblemAssignmentRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.ExamRow", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mastemis.Infrastructure.Persistence.Problems.ProblemDraftRow", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.GeneratedTestRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.Problems.GeneratedTestSetRow", null)
                        .WithMany()
                        .HasForeignKey("TestSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.GeneratedTestSetRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.Problems.ProblemDraftRow", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemAuthorAssignmentRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.Problems.ProblemDraftRow", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mastemis.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemGenerationOperationRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.Problems.ProblemDraftRow", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.Problems.ProblemStatementRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.Problems.ProblemDraftRow", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.RoomRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.ExamRow", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.CandidateRow", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mastemis.Infrastructure.Persistence.ExamRow", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mastemis.Infrastructure.Persistence.RoomRow", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SfeEvaluationRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.SfeEventRow", null)
                        .WithOne()
                        .HasForeignKey("Mastemis.Infrastructure.Persistence.SfeEvaluationRow", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SfeEventRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SourceRevisionRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.SubmissionRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.SourceRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mastemis.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.WarningRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.SfeEvaluationRow", null)
                        .WithOne()
                        .HasForeignKey("Mastemis.Infrastructure.Persistence.WarningRow", "EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mastemis.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mastemis.Infrastructure.Persistence.WorkerCredentialRow", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.JudgeWorkerRow", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mastemis.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Mastemis.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
